version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      zacal:
        ipv4_address: 10.8.0.2

  core:
    build: ./packages/core
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./packages/core:/app
    env_file: .env
    ports:
      - 7001:7001
      - 9000:9000
    networks:
      zacal:
        ipv4_address: 10.8.0.3

  web:
    build: ./packages/web
    restart: always
    volumes:
      - ./packages/web:/app
    env_file: .env
    ports:
      - 8000:8000
    networks:
      zacal:
        ipv4_address: 10.8.0.4

networks:
  zacal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
