version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ./.docker-volumes/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      zacal:
        ipv4_address: 10.9.0.2
  core:
    build: ./packages/core
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./packages/core:/app
    env_file: .env
    ports:
      - 7001:7001
      - 9000:9000
    networks:
      zacal:
        ipv4_address: 10.9.0.3

  web:
    build: ./packages/web
    restart: always
    volumes:
      - ./packages/web:/app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

    networks:
      zacal:
        ipv4_address: 10.9.0.4
  cms:
    image: directus/directus:10.10.4
    ports:
      - 8055:8055
    volumes:
      - ./.docker-volumes/database:/directus/database
      - ./.docker-volumes/uploads:/directus/uploads
      - ./.docker-volumes/extensions:/directus/extensions
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      zacal:
        ipv4_address: 10.9.0.5


networks:
  zacal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/16
          gateway: 10.9.0.1
